"""Deterministic LaTeX document assembly.

No LLM in this module. The prose proof is already produced (and grounded in
the verified Lean proof) upstream; here we only do mechanical work:
- unicode -> LaTeX symbol conversion for Lean statements and goal states
- parsing the prose into Theorem / Proof sections
- assembling a complete, compilable .tex document (amsart-style article with
  amsthm environments, plus the machine-verified Lean proof in an appendix)
"""
from __future__ import annotations

import re

# Symbol table for rendering Lean statements/goals as LaTeX math. Purely
# mechanical — no interpretation, no model.
LEAN_TO_LATEX = {
    "ℕ": r"\mathbb{N}", "ℤ": r"\mathbb{Z}", "ℚ": r"\mathbb{Q}",
    "ℝ": r"\mathbb{R}", "ℂ": r"\mathbb{C}",
    "∀": r"\forall ", "∃": r"\exists ", "¬": r"\neg ",
    "∧": r"\land ", "∨": r"\lor ", "↔": r"\leftrightarrow ",
    "→": r"\to ", "←": r"\leftarrow ", "↦": r"\mapsto ",
    "≤": r"\le ", "≥": r"\ge ", "≠": r"\ne ", "∣": r"\mid ",
    "∈": r"\in ", "∉": r"\notin ", "⊆": r"\subseteq ", "⊂": r"\subset ",
    "∩": r"\cap ", "∪": r"\cup ", "∅": r"\emptyset ",
    "∑": r"\sum", "∏": r"\prod", "∫": r"\int",
    "√": r"\sqrt", "∞": r"\infty ", "⊢": r"\vdash ",
    "α": r"\alpha ", "β": r"\beta ", "γ": r"\gamma ", "δ": r"\delta ",
    "ε": r"\varepsilon ", "λ": r"\lambda ", "μ": r"\mu ", "π": r"\pi ",
    "σ": r"\sigma ", "φ": r"\varphi ", "ω": r"\omega ",
    "⁻¹": r"^{-1}", "²": r"^{2}", "³": r"^{3}",
    "×": r"\times ", "∘": r"\circ ", "⟨": r"\langle ", "⟩": r"\rangle ",
    "≃": r"\simeq ", "≅": r"\cong ", "≡": r"\equiv ",
}

THEOREM_PROOF_RE = re.compile(
    r"\*\*Theorem\.?\*\*\s*(?P<statement>.+?)\s*\*\*Proof\.?\*\*\s*(?P<proof>.+)",
    re.DOTALL,
)


def lean_symbols_to_latex(text: str) -> str:
    """Convert a Lean statement or goal's unicode symbols to LaTeX macros."""
    for symbol, macro in LEAN_TO_LATEX.items():
        text = text.replace(symbol, macro)
    return text


def split_theorem_and_proof(prose: str) -> tuple[str, str]:
    """Split the structured prose into (statement, proof body).

    Falls back to ("", whole prose) when the expected **Theorem.**/**Proof.**
    markers are missing (e.g. old-format answers, explanation questions).
    """
    match = THEOREM_PROOF_RE.search(prose)
    if not match:
        return "", prose.strip()
    return match.group("statement").strip(), match.group("proof").strip()


def _markdown_to_latex(text: str) -> str:
    """Minimal markdown -> LaTeX for the prose (math is already LaTeX)."""
    text = re.sub(r"^#{1,3}\s*(.+)$", r"\\subsection*{\1}", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"\\emph{\1}", text)
    text = re.sub(r"`([^`]+)`", r"\\texttt{\1}", text)
    # $$...$$ display math -> \[...\]
    text = re.sub(r"\$\$(.+?)\$\$", r"\\[\1\\]", text, flags=re.DOTALL)
    return text.strip()


def build_latex_document(
    question: str,
    prose: str,
    lean_statement: str = "",
    lean_proof: str = "",
    verification: str = "unverified",
) -> str:
    """Assemble a complete .tex document. Pure string building."""
    statement, proof_body = split_theorem_and_proof(prose)

    parts: list[str] = [
        "% Generated by Axlerate",
        r"\documentclass[11pt]{article}",
        r"\usepackage{amsmath, amssymb, amsthm}",
        r"\usepackage[margin=1in]{geometry}",
        r"\newtheorem{theorem}{Theorem}",
        "",
        r"\title{" + _escape_text(question) + "}",
        r"\date{}",
        "",
        r"\begin{document}",
        r"\maketitle",
        "",
    ]

    if statement:
        parts += [r"\begin{theorem}", _markdown_to_latex(statement), r"\end{theorem}", ""]
    # \end{proof} prints its own QED square — drop a trailing ∎/blacksquare
    proof_body = re.sub(r"\s*\$?(\\blacksquare|∎|□)\$?\s*$", "", proof_body)
    parts += [r"\begin{proof}", _markdown_to_latex(proof_body), r"\end{proof}", ""]

    # The document stays pure mathematical prose — no Lean code. The
    # formalization lives in the app's Lean panel; here it's one line of
    # provenance, the way a paper would acknowledge a formal verification.
    if verification == "lean-verified" and lean_statement:
        parts += [
            r"\vspace{1em}\noindent\begin{small}\emph{This theorem has been "
            r"formalized and its proof machine-verified with the Lean~4 "
            r"proof assistant.}\end{small}",
            "",
        ]
    elif verification == "ai-reviewed":
        parts += [
            r"\vspace{1em}\noindent\begin{small}\emph{This proof was reviewed "
            r"by an AI grader and has not been machine-verified by a proof "
            r"assistant.}\end{small}",
            "",
        ]

    parts.append(r"\end{document}")
    return "\n".join(parts)


def _escape_text(text: str) -> str:
    for char, escaped in [
        ("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
    ]:
        text = text.replace(char, escaped)
    return text


